### PR TITLE
Avoid hypocrisy by translating the git command itself

### PR DESCRIPTION
**Pull request by nachokb**
## Defect

I couldn't help but notice the hypocrisy behind translating git subcommands while not translating the git command itself.

This PR is an attempt to solve this problem.

## Proposed solution

Implement an alias for git. Currently tested on bash.

### CODE REVIEW

**Comment by lucasefe** [comment]
I like where your head is at.

Let's consider a few alternatives:

http://www.spanishdict.com/translate/git
screenshot 2018-03-10 08 35 12

**Comment by lucasefe** [comment]
I like where your head is at.

Let's consider a few alternatives: http://www.spanishdict.com/translate/git
screenshot 2018-03-10 08 35 12

This as well:

https://dictionary.cambridge.org/dictionary/english-spanish/git screenshot 2018-03-10 08 36 14

I like cretino a lot, but canalla is very nice (I think both makes sense, to be honest). 

Should we take a vote? What do you think, @j0an?

**Comment by nachokb** [comment]
Like this comment for `cretino`

**Comment by nachokb** [comment]
Like this comment for `canalla`

**Comment by nachokb** [comment]
maybe we should just call it "linus" :stuck_out_tongue_closed_eyes:

**Review by lucasefe — APPROVED** [review]

**Pull request merged**
